### ISSUE TITLE
Adicionar a página "Cantina" aos outros cargos 

### ISSUE THREAD

**Issue by ColegioFantastico** [sr-pato/CantinaCF#2]
No momento, somente Administrador e Aluno tem acesso a página da cantina, peço que retire a página dos produtos da cantina de todos os cargos com excessão apenas dos administradores e adicionar a página de cantina para todos os cargos, obrigado!

**Comment by felipeadeildo** [comment]
A partir deste [commit](https://github.com/sr-pato/CantinaCF/commit/797f4f1a7ae708026e1505149a5c055317c01874) é possível fazer gerenciamento de rotas por cargo, portanto a partir de agora usuário que tenha permissão de acessar a rota `roles` consegue editar as rotas em que os cargos podem acessar, assim basta adicionar permissão ao cargo "Funcionário" as rotas que permitem usar a Cantina, como descrito nas imagens abaixo:

![image](https://github.com/sr-pato/CantinaCF/assets/112831443/9e381787-94de-4197-8908-a34216e0e069)
![image](https://github.com/sr-pato/CantinaCF/assets/112831443/52cad15a-9acb-4675-bf2d-84974fa6252b)
