### ISSUE TITLE
Fix some bugs and add functionalities

### ISSUE THREAD

**Issue by ColegioFantastico** [sr-pato/CantinaCF#3]
* corrigir o bug de compra mútipla no sistema na aba de confirmar a compra do carrinho
         exemplos do ID 2,38

* Corrigir necessidade de inserir senha antiga na aba de alterar senha de usuário como ADMIN

* alterar vizualização da compra na aba de Despacho, para ser por Usuário e não somente id de venda

**Comment by felipeadeildo** [comment]
Fixed bugs now:

- Multiple submit on Confirm Purcharse 

Changes now:
- To Despatch page received a new visualization (frontend)
- Added animation on submit forms


TO DO:
- Fix bug on change password with an admin logged user
- To export products in session user to a table on database or to add cache system that resets the product again when he's on user cart for a long time. 
- Add an outstanding balance preview page (payroll)
- Add admin option to edit saldo_payroll when paid out

**Comment by felipeadeildo** [comment]
Fixed now:

- Bug on change passwrd with an admin logged user
- Bug on paypayroll

TODO:

- To export products in session user to a table on database or to add cache system that resets the product again when he's on user cart for a long time.
- Add an outstanding balance preview page (payroll)
- Add admin option to edit saldo_payroll when paid out

**Comment by ColegioFantastico** [comment]
* exclude the necessitie to put the ID or any login, for role "aluno" on "cantina" to buy something, needing just to put the pswrd
* add some function tha permits "admin" to make a solicitation of recharge in any acount, by the id or user of that acount who's wanting that recharge
* make a table for payments on the payroll debt for the "admin" to insert the payments refering to all discounts in the next payroll
* make a page or add the possibility to lookup user with "saldo_devedor" on "usuários_com_saldo_disponível" or in other page if not possibly do that in this same page

**Comment by felipeadeildo** [comment]
Fixed now:
- To export products in session user to a table on database or to add cache system that resets the product again when he's on user cart for a long time.
- Add an outstanding balance preview page (payroll)

To do:
- Add admin option to edit saldo_payroll when paid out
- Exclude the necessitie to put the ID or any login, for role "aluno" on "cantina" to buy something, needing just to put the pasword
- Add function that allow "admin" role to make a  recharge solicitation in any acount, by the id or username of that acount who's wanting that recharge
- To make a table for payments on the payroll debt for the "admin" to insert the payments refering to all discounts in the next payroll

**Comment by felipeadeildo** [comment]
Fixed Now:
- Exclude the necessitie to put the ID or any login, for role "aluno" on "cantina" to buy something, needing just to put the pasword

To do:
- Add admin option to edit saldo_payroll when paid out
- Add function that allow "admin" role to make a recharge solicitation in any acount, by the id or username of that acount who's wanting that recharge
- To make a table for payments on the payroll debt for the "admin" to insert the payments refering to all discounts in the next payroll

**Comment by felipeadeildo** [comment]
Fixed Now:

- Add function that allow "admin" role to make a recharge solicitation in any acount, by the id or username of that acount who's wanting that recharge

To do:

- Add admin option to edit saldo_payroll when paid out
- To make a table for payments on the payroll debt for the "admin" to insert the payments refering to all discounts in the next payroll
