### ISSUE TITLE
Novas solicitações para o CF Cantina

### ISSUE THREAD

**Issue by ColegioFantastico** [sr-pato/CantinaCF#4]
* Página dos saldos devedores
      Necessária a inclusão de uma página para a verificação dos saldos devedores
             pode ser na mesma página de usuários com saldo
      Necessário também colocar um mecânismo de resolução do débito de forma mais ativa para o administrador
             uma forma de colocar isso seria uma página dos devedores com o saldo devedor e colocar um pagamento ativo ao lado de cada saldo, onde o usuário possa colocar o valor a ser reduzido da dívida

* Recarga rápida
       inserir um método de recarga diretamente para a conta do aluno sem a necessidade de entrar na conta desse aluno, pelo id, matrícula ou usuário na página de recarga ou outra carga

* Compra na página do aluno ser direta
        Tirar a necessidade do cargo aluno depois de logado, ter que colocar o id novamente para realizar a compra na cantina, tornar necessário apenas a senha

**Comment by felipeadeildo** [comment]
In progress in another issue request.

The issue is [this](https://github.com/sr-pato/CantinaCF/issues/3)
